[package]
name = "livekit-tui-client"
version = "0.1.0"
edition = "2021"
default-run = "client"
autobins = false

[[bin]]
name = "client"
path = "src/bin/client.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
crossterm = "0.28"
ratatui = "0.29"
livekit = { version = "0.7", features = ["native-tls"] }
cpal = "0.15"
nokhwa = { version = "0.10", features = ["input-native"] }
futures-util = "0.3"
dotenvy = "0.15"
terminal-pixel-animation = "0.4.0"

# Token generation & Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9.3"
